---
################################################################################
#
# This file defines the environment variables to be added to the project
#
# Each parent should follow the following structure
#
# [files : list of relative paths from the root of the project to the files]
# The reason why there can be multiple is to hold an example environment file
#
# [parent : name to be referenced by]
#   - [comment : (optional) comment to be added above the block]
#   - [variables : list of environment variables]
#       [key : name of the key]
#       [value : the value the key will hold]
#       [generate : (optional) length of key to be generated instead of value]
#
################################################################################

################################################################################
#
# FILE
#
# The file where the resource routes are defined
################################################################################
files:
  - .env
  - .env.example

################################################################################
#
# AUTHENTICATION
#
################################################################################
authentication:
  comment: Environment data for the JWT token
  variables:
    - key: JWT_SECRET
      generate: 16
    - key: JWT_EXPIRES_IN
      value: 30d
